### ISSUE TITLE
Suggestions on Equipment List

### ISSUE THREAD

**Issue by lloydlentz** [kthull/session-recording#11]
There is no way to make a Pull Request on wiki pages.   So, I made some suggestions to your equipment list https://github.com/lloydlentz/session-recording/wiki/Equipment-List

**Comment by kthull** [comment]
Thanks so much @lloydlentz! I will add the note and definitely test out the USB A to C drive. I'll also see about converting the wiki to plain old html for PRs.

**Comment by lloydlentz** [comment]
I think if you just move the .md files to the root, then they should read the same, and would allow for pull requests.   I did spend a while trying to research how to make a pull request to a wiki.  Seems like they are different purposes.  

Also, this documentation is HUGE.  I am really digging this setup and we are about to have 8 recording setups at our DevFestMN event.  I'll let you know how it turns out.

**Comment by kthull** [comment]
I'm so excited to hear it!! Definitely ping me for ANY help you need.
Overall, UST is a solid venue with these kits.
-Kevin

**Comment by kthull** [comment]
I tested the USB A to C drives and experienced no issues, so I've added it as an alternate drive in the equipment list. Thanks @lloydlentz!
